import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { HeaderElement } from './ui/header/header'
import { FooterElement } from './ui/footer/footer'
import { SessionProvider } from './context/session-context'

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
})
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
})

export const metadata: Metadata = {
	title: 'Fantasy Hockey Cheatsheet',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<SessionProvider>
					<HeaderElement />
					<div className="max-w-screen-2xl w-full mx-auto px-4 sm:px-2">{children}</div>
					<FooterElement />
				</SessionProvider>
			</body>
		</html>
	)
}
